import { NextResponse } from "next/server";

export async function GET() {
  const script = `# Auto-generated by Project Prometheus LoRA/QLoRA Pipeline
import torch
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from trl import SFTTrainer

# 1. 4-Bit NormalFloat (NF4) QLoRA Configuration
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)

# 2. Load Base Model and Tokenizer
model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)
model = prepare_model_for_kbit_training(model)

# 3. LoRA Adapter Configuration
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
)
model = get_peft_model(model, peft_config)

# 4. Training Arguments
training_args = TrainingArguments(
    output_dir="./prometheus-lora-adapter",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    logging_steps=10,
    num_train_epochs=3,
    optim="paged_adamw_8bit",
    bf16=True,
    report_to="none",
)

# 5. Execute SFTTrainer
dataset = load_dataset("json", data_files="prometheus_golden_traces.jsonl", split="train")
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    max_seq_length=2048,
    tokenizer=tokenizer,
    args=training_args,
)
trainer.train()
trainer.model.save_pretrained("./prometheus-lora-adapter")
print("LoRA adapter training completed successfully.")
`;

  return NextResponse.json({
    framework: "Hugging Face TRL (SFTTrainer)",
    base_model: "meta-llama/Meta-Llama-3-8B-Instruct",
    script,
  });
}
