"""add model index to usage_records

Revision ID: 048fa8e0c0dc
Revises: 16695cabd80f
Create Date: 2026-09-03 19:15:31.434001
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '048fa8e0c0dc'
down_revision: Union[str, None] = '16695cabd80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_model'), ['model'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_model'))

    op.create_table('document_vectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_vectors')),
    sa.UniqueConstraint('chunk_id', name=op.f('uq_document_vectors_chunk_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('document_vectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_vectors_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###
