# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service/proto/inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ml_service/proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ml_service/proto/inference.proto\x12\tinference\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"j\n\x0fPredictResponse\x12\x18\n\x10\x63omplexity_class\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x12\n\nlatency_ms\x18\x03 \x01(\x02\x12\x15\n\rmodel_version\x18\x04 \x01(\t\"$\n\x13\x42\x61tchPredictRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"o\n\x14\x42\x61tchPredictResponse\x12/\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x1a.inference.PredictResponse\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x12\n\nlatency_ms\x18\x03 \x01(\x02\x32\xa5\x01\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12O\n\x0cPredictBatch\x12\x1e.inference.BatchPredictRequest\x1a\x1f.inference.BatchPredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service.proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=47
  _globals['_PREDICTREQUEST']._serialized_end=77
  _globals['_PREDICTRESPONSE']._serialized_start=79
  _globals['_PREDICTRESPONSE']._serialized_end=185
  _globals['_BATCHPREDICTREQUEST']._serialized_start=187
  _globals['_BATCHPREDICTREQUEST']._serialized_end=223
  _globals['_BATCHPREDICTRESPONSE']._serialized_start=225
  _globals['_BATCHPREDICTRESPONSE']._serialized_end=336
  _globals['_INFERENCESERVICE']._serialized_start=339
  _globals['_INFERENCESERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
